# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Full Stack Developer"
  name: "Xavier Montalvo"
  username: "xmontalvvo" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "montalvox27@gmail.com"
    icon: "mail-outline"
  - label: "Teléfono"
    value: "+593 939366764"
    icon: "phone-portrait-outline"
  - label: "Cumpleaños"
    value: "Octubre 25, 1998"
    icon: "calendar-outline"
  - label: "Ubicación"
    value: "Quito, Ecuador"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/"
  - icon: "logo-github"
    url: "https://github.com/ivansaul"
